### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by CleverPlotDevice** [greedyj4ck/degenesis-db#1]
Clear instructions as to how to upload this file into Foundry and access it in the VTT would be wonderful.  Or merely even including it in the main download.

**Comment by greedyj4ck** [comment]
Hi :) 

Sorry for late response. 

Those are universal JSON entries - there need to be parsed to match values used in degenesis system and foundry's API. 
I am currently during process of migrating data into Foundry's format, gonna share file later, but it will be also included with system update in official pack. 

Just few more days :) There are some minor fixes left ;) 
![image](https://user-images.githubusercontent.com/33233389/105771203-7a66f900-5f60-11eb-90ff-9cd1e2aae35e.png)

I will also share example import scripts with the next push.

**Comment by greedyj4ck** [comment]
Created pull request at https://github.com/moo-man/DEGENESIS-FoundryVTT/pull/18.
